<script>
	import { onMount } from 'svelte';
	import pixelmatch from 'pixelmatch';
	import Tesseract from 'tesseract.js';
	import { Upload, Scan, Scale, AlertCircle, CheckCircle2 } from 'lucide-svelte';
	import PageContainer from '$lib/components/ui/PageContainer.svelte';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import CardHeader from '$lib/components/ui/CardHeader.svelte';

	// -- State Variables --
	let file1, file2; // File inputs (not strictly bound but useful if needed)
	let img1Url, img2Url; // Blob URLs for the uploaded images
	let canvas; // Reference to a canvas element (if needed for direct manipulation)
	let diffUrl; // Blob URL for the difference image generated by pixelmatch
	let ocrResult = ''; // Text result from OCR
	let ocrStatus = ''; // Status message for OCR progress
	let matchResult = null; // Object containing comparison stats (percentage, diff pixels)
	let isProcessing = false; // Loading state for async operations

	/**
	 * Handles file selection for both image inputs.
	 * Creates a local object URL for preview and processing.
	 * @param {Event} event - The input change event
	 * @param {number} num - 1 for Image 1, 2 for Image 2
	 */
	function handleFileUpload(event, num) {
		const file = event.target.files[0];
		if (!file) return;

		const url = URL.createObjectURL(file);
		if (num === 1) {
			img1Url = url;
		} else {
			img2Url = url;
		}
	}

	/**
	 * Helper function to load an image from a URL and extract its pixel data.
	 * Draws the image to an off-screen canvas to get ImageData.
	 * @param {string} url - The image URL
	 * @returns {Promise<{data: Uint8ClampedArray, width: number, height: number, imgElement: HTMLImageElement}>}
	 */
	async function getImageData(url) {
		return new Promise((resolve, reject) => {
			const img = new Image();
			img.onload = () => {
				const c = document.createElement('canvas');
				c.width = img.width;
				c.height = img.height;
				const ctx = c.getContext('2d');
				ctx.drawImage(img, 0, 0);
				resolve({
					data: ctx.getImageData(0, 0, img.width, img.height).data,
					width: img.width,
					height: img.height,
					imgElement: img
				});
			};
			img.onerror = reject;
			img.src = url;
		});
	}

	/**
	 * Compares Image 1 and Image 2 using pixelmatch.
	 * Resizes Image 2 to match Image 1 if dimensions differ.
	 * Generates a visual diff image and calculates difference percentage.
	 */
	async function compareImages() {
		if (!img1Url || !img2Url) return;
		isProcessing = true;
		matchResult = null;
		diffUrl = null;

		try {
			// 1. Get raw pixel data for both images
			const img1 = await getImageData(img1Url);
			const img2 = await getImageData(img2Url);

			// 2. Handle dimension mismatch (resize img2 to img1)
			if (img1.width !== img2.width || img1.height !== img2.height) {
				// Create a temporary canvas to resize img2
				const c = document.createElement('canvas');
				c.width = img1.width;
				c.height = img1.height;
				const ctx = c.getContext('2d');
				ctx.drawImage(img2.imgElement, 0, 0, img1.width, img1.height);
				const resizedImg2Data = ctx.getImageData(0, 0, img1.width, img1.height).data;

				img2.data = resizedImg2Data;
				img2.width = img1.width;
				img2.height = img1.height;
			}

			// 3. Prepare diff output canvas
			const diffCanvas = document.createElement('canvas');
			diffCanvas.width = img1.width;
			diffCanvas.height = img1.height;
			const diffCtx = diffCanvas.getContext('2d');
			const diffImgData = diffCtx.createImageData(img1.width, img1.height);

			// 4. Run pixelmatch
			const numDiffPixels = pixelmatch(
				img1.data,
				img2.data,
				diffImgData.data,
				img1.width,
				img1.height,
				{ threshold: 0.1 } // Sensitivity threshold (0.1 is standard)
			);

			// 5. Display results
			diffCtx.putImageData(diffImgData, 0, 0);
			diffUrl = diffCanvas.toDataURL();
			const diffPercent = (numDiffPixels / (img1.width * img1.height)) * 100;
			matchResult = {
				diffPixels: numDiffPixels,
				totalPixels: img1.width * img1.height,
				diffPercentage: diffPercent.toFixed(2),
				similarityPercentage: (100 - diffPercent).toFixed(2)
			};
		} catch (e) {
			console.error(e);
			alert('Error comparing images');
		} finally {
			isProcessing = false;
		}
	}

	/**
	 * Runs OCR on Image 1 using Tesseract.js.
	 * Updates status during processing and displays final text.
	 */
	async function runOCR() {
		if (!img1Url) return;
		isProcessing = true;
		ocrResult = '';
		ocrStatus = 'Initializing...';

		try {
			// Perform OCR with progress logging
			const result = await Tesseract.recognize(
				img1Url,
				'eng', // Default to English (eng). Could be 'jpn' or 'kor' for BA.
				{
					logger: (m) => (ocrStatus = `OCR: ${m.status} (${(m.progress * 100).toFixed(0)}%)`)
				}
			);
			ocrResult = result.data.text;
			ocrStatus = 'Done';
		} catch (e) {
			console.error(e);
			ocrStatus = 'Error: ' + e.message;
		} finally {
			isProcessing = false;
		}
	}
</script>

<PageContainer
	title="Image Match & OCR Tool"
	description="Compare two images and extract text using OCR."
>
	<PageHeader title="Image Analysis" description="Upload images to compare or scan text." />

	<div class="grid gap-6 md:grid-cols-2">
		<!-- Image 1 Input -->
		<Card class="flex flex-col">
			<CardHeader title="Image 1 (Source)" icon={Upload} />
			<div class="flex flex-1 flex-col gap-4 p-4">
				<input
					type="file"
					accept="image/*"
					class="block w-full text-sm text-slate-500
						file:mr-4 file:rounded-full file:border-0
						file:bg-cyan-50 file:px-4
						file:py-2 file:text-sm
						file:font-semibold file:text-cyan-700
						hover:file:bg-cyan-100"
					on:change={(e) => handleFileUpload(e, 1)}
				/>
				<div
					class="relative flex aspect-video items-center justify-center overflow-hidden rounded-lg border-2 border-dashed border-slate-300 bg-slate-100"
				>
					{#if img1Url}
						<img
							src={img1Url}
							alt="Preview 1"
							class="absolute inset-0 h-full w-full object-contain"
						/>
					{:else}
						<span class="text-slate-400">No Image Selected</span>
					{/if}
				</div>
				<div class="flex gap-2">
					<button
						class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-2 font-bold text-white transition-colors hover:bg-cyan-700 disabled:cursor-not-allowed disabled:opacity-50"
						disabled={!img1Url || isProcessing}
						on:click={runOCR}
					>
						<Scan size={18} />
						Run OCR (Img 1)
					</button>
				</div>
			</div>
		</Card>

		<!-- Image 2 Input -->
		<Card class="flex flex-col">
			<CardHeader title="Image 2 (Compare)" icon={Upload} />
			<div class="flex flex-1 flex-col gap-4 p-4">
				<input
					type="file"
					accept="image/*"
					class="block w-full text-sm text-slate-500
						file:mr-4 file:rounded-full file:border-0
						file:bg-cyan-50 file:px-4
						file:py-2 file:text-sm
						file:font-semibold file:text-cyan-700
						hover:file:bg-cyan-100"
					on:change={(e) => handleFileUpload(e, 2)}
				/>
				<div
					class="relative flex aspect-video items-center justify-center overflow-hidden rounded-lg border-2 border-dashed border-slate-300 bg-slate-100"
				>
					{#if img2Url}
						<img
							src={img2Url}
							alt="Preview 2"
							class="absolute inset-0 h-full w-full object-contain"
						/>
					{:else}
						<span class="text-slate-400">No Image Selected</span>
					{/if}
				</div>
				<div class="flex gap-2">
					<button
						class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-violet-600 px-4 py-2 font-bold text-white transition-colors hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-50"
						disabled={!img1Url || !img2Url || isProcessing}
						on:click={compareImages}
					>
						<Scale size={18} />
						Compare Images
					</button>
				</div>
			</div>
		</Card>
	</div>

	<!-- Results Section -->
	{#if diffUrl || ocrResult || ocrStatus}
		<div class="mt-8 space-y-6">
			{#if matchResult}
				<Card>
					<CardHeader title="Comparison Result" icon={CheckCircle2} />
					<div class="space-y-4 p-4">
						<div class="flex flex-wrap items-center gap-3 text-sm">
							<div class="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-700">
								Similarity: {matchResult.similarityPercentage}%
							</div>
							<div class="rounded-full bg-slate-100 px-3 py-1 text-slate-600">
								Difference: <span
									class="font-bold {matchResult.diffPercentage > 5
										? 'text-red-500'
										: 'text-green-600'}">{matchResult.diffPercentage}%</span
								>
							</div>
							<div class="text-xs text-slate-500">
								({matchResult.diffPixels} pixels differ)
							</div>
						</div>
						<div
							class="relative flex aspect-video items-center justify-center overflow-hidden rounded-lg bg-black"
						>
							<img src={diffUrl} alt="Diff" class="absolute inset-0 h-full w-full object-contain" />
						</div>
					</div>
				</Card>
			{/if}

			{#if ocrResult || ocrStatus}
				<Card>
					<CardHeader title="OCR Result (Image 1)" icon={Scan} />
					<div class="space-y-2 p-4">
						{#if ocrStatus && ocrStatus !== 'Done'}
							<div class="animate-pulse text-sm font-medium text-cyan-600">{ocrStatus}</div>
						{/if}

						{#if ocrResult}
							<div
								class="max-h-96 overflow-y-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-sm whitespace-pre-wrap text-slate-700"
							>
								{ocrResult}
							</div>
						{:else if ocrStatus === 'Done'}
							<div class="text-sm text-slate-400 italic">No text detected.</div>
						{/if}
					</div>
				</Card>
			{/if}
		</div>
	{/if}
</PageContainer>
